version: '3'
services:
  serfagent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    ports:
      - '7946:7946'
      - '7373:7373'
    environment:
      SELF_IP: "172.29.20.2"
  serfjoiner:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    environment:
      SERF_HOST: "172.29.20.2"
      SERF_PORT: 7373
      TABLE_NAME: testserfmembers
      AWS_REGION: us-east-1
    env_file:
    - .env
    depends_on:
    - serfagent
  serfreporter:
    build:
      context: .
      dockerfile: reporter/Dockerfile
    environment:
      MY_IP: "172.29.20.2"
      TABLE_NAME: testserfmembers
      AWS_REGION: us-east-1
    env_file:
    - .env
    depends_on:
    - serfagent
