version: '3'
services:
  serfagent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    ports:
      - '7946:7946'
      - '7373:7373'
    environment:
      SELF_IP: serfagent
  serfjoiner:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    environment:
      SERF_HOST: serfagent
      SERF_PORT: 7373
    depends_on:
    - serfagent
  serfreporter:
    build:
      context: .
      dockerfile: reporter/Dockerfile
    environment:
      MY_IP: "1.2.3.4" # something fake for now
      TABLE_NAME: testserfmembers
      AWS_REGION: us-east-1
    env_file:
    - .env
    depends_on:
    - serfagent
